"""
Gmail SMTP automation service
Send emails with RAG answers, reports, and summaries
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from typing import List, Optional, Dict
from datetime import datetime
import os
from app.utils.logger import app_logger
from app.config import settings


class GmailService:
    """
    Gmail automation service using SMTP
    """
    
    def __init__(self):
        """Initialize Gmail service"""
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587
        self.sender_email = os.getenv("GMAIL_EMAIL")
        self.sender_password = os.getenv("GMAIL_APP_PASSWORD")  # App-specific password
        self.enabled = bool(self.sender_email and self.sender_password)
        
        if not self.enabled:
            app_logger.warning("Gmail service not configured. Set GMAIL_EMAIL and GMAIL_APP_PASSWORD")
    
    def send_email(
        self,
        to_email: str,
        subject: str,
        body: str,
        body_html: Optional[str] = None,
        attachments: Optional[List[str]] = None
    ) -> Dict[str, any]:
        """
        Send email via Gmail SMTP
        
        Args:
            to_email: Recipient email
            subject: Email subject
            body: Plain text body
            body_html: HTML body (optional)
            attachments: List of file paths to attach
        
        Returns:
            Status dictionary
        """
        if not self.enabled:
            return {
                "success": False,
                "error": "Gmail service not configured"
            }
        
        try:
            # Create message
            msg = MIMEMultipart('alternative')
            msg['From'] = self.sender_email
            msg['To'] = to_email
            msg['Subject'] = subject
            msg['Date'] = datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S +0000')
            
            # Add plain text body
            msg.attach(MIMEText(body, 'plain'))
            
            # Add HTML body if provided
            if body_html:
                msg.attach(MIMEText(body_html, 'html'))
            
            # Add attachments
            if attachments:
                for filepath in attachments:
                    if os.path.exists(filepath):
                        with open(filepath, 'rb') as f:
                            part = MIMEApplication(f.read(), Name=os.path.basename(filepath))
                            part['Content-Disposition'] = f'attachment; filename="{os.path.basename(filepath)}"'
                            msg.attach(part)
            
            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)
            
            app_logger.info(f"Email sent successfully to {to_email}")
            
            return {
                "success": True,
                "to": to_email,
                "subject": subject,
                "sent_at": datetime.utcnow().isoformat()
            }
        
        except Exception as e:
            app_logger.error(f"Failed to send email: {str(e)}")
            return {
                "success": False,
                "error": str(e)
            }
    
    def send_rag_answer(
        self,
        to_email: str,
        question: str,
        answer: str,
        sources: List[Dict],
        user_name: Optional[str] = None
    ) -> Dict[str, any]:
        """
        Send RAG answer via email
        
        Args:
            to_email: Recipient email
            question: User question
            answer: Generated answer
            sources: Source citations
            user_name: User's name
        
        Returns:
            Status dictionary
        """
        greeting = f"Hello {user_name}," if user_name else "Hello,"
        
        # Plain text version
        body = f"""{greeting}

Here is the answer to your question:

QUESTION:
{question}

ANSWER:
{answer}

SOURCES:
"""
        for i, source in enumerate(sources):
            body += f"\n{i+1}. {source['filename']}"
            if source.get('page_number'):
                body += f" (Page {source['page_number']})"
        
        body += f"""

---
This email was automatically generated by Regnova Knowledge Assistant.
Generated at: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}
"""
        
        # HTML version
        body_html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
        .header {{ background-color: #4A90E2; color: white; padding: 20px; border-radius: 5px; }}
        .content {{ background-color: #f9f9f9; padding: 20px; margin-top: 20px; border-radius: 5px; }}
        .question {{ font-weight: bold; color: #4A90E2; }}
        .answer {{ margin-top: 15px; }}
        .sources {{ margin-top: 20px; background-color: white; padding: 15px; border-left: 3px solid #4A90E2; }}
        .source-item {{ margin: 5px 0; }}
        .footer {{ margin-top: 20px; font-size: 12px; color: #777; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>Regnova Knowledge Assistant</h2>
        </div>
        
        <div class="content">
            <p>{greeting}</p>
            
            <p>Here is the answer to your question:</p>
            
            <div class="question">
                <strong>QUESTION:</strong><br>
                {question}
            </div>
            
            <div class="answer">
                <strong>ANSWER:</strong><br>
                {answer.replace(chr(10), '<br>')}
            </div>
            
            <div class="sources">
                <strong>SOURCES:</strong><br>
"""
        
        for i, source in enumerate(sources):
            page_info = f" (Page {source['page_number']})" if source.get('page_number') else ""
            body_html += f'<div class="source-item">{i+1}. {source["filename"]}{page_info}</div>'
        
        body_html += f"""
            </div>
        </div>
        
        <div class="footer">
            <p>This email was automatically generated by Regnova Knowledge Assistant.</p>
            <p>Generated at: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
        </div>
    </div>
</body>
</html>
"""
        
        subject = f"Answer: {question[:50]}..." if len(question) > 50 else f"Answer: {question}"
        
        return self.send_email(to_email, subject, body, body_html)
    
    def send_report(
        self,
        to_email: str,
        report_data: Dict,
        pdf_path: Optional[str] = None
    ) -> Dict[str, any]:
        """
        Send generated report via email
        
        Args:
            to_email: Recipient email
            report_data: Report data dictionary
            pdf_path: Optional PDF attachment path
        
        Returns:
            Status dictionary
        """
        subject = f"Report: {report_data.get('title', 'Knowledge Assistant Report')}"
        
        body = f"""Hello,

Please find attached your generated report from Regnova Knowledge Assistant.

Report Title: {report_data.get('title', 'N/A')}
Generated: {report_data.get('generated_at', datetime.utcnow().isoformat())}
Total Files: {report_data.get('total_files', 0)}
Total Queries: {report_data.get('total_queries', 0)}

Best regards,
Regnova Knowledge Assistant
"""
        
        attachments = [pdf_path] if pdf_path and os.path.exists(pdf_path) else None
        
        return self.send_email(to_email, subject, body, attachments=attachments)
    
    def send_notification(
        self,
        to_email: str,
        notification_type: str,
        message: str,
        data: Optional[Dict] = None
    ) -> Dict[str, any]:
        """
        Send notification email
        
        Args:
            to_email: Recipient email
            notification_type: Type of notification
            message: Notification message
            data: Additional data
        
        Returns:
            Status dictionary
        """
        subject = f"Notification: {notification_type}"
        
        body = f"""Hello,

{message}

---
Regnova Knowledge Assistant
{datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}
"""
        
        return self.send_email(to_email, subject, body)


# Global instance
gmail_service = GmailService()
