"""
Gmail automation service for sending emails
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from typing import List, Optional
from app.utils.logger import app_logger
from app.config import settings
import os


class GmailService:
    """Service for Gmail automation"""
    
    def __init__(self):
        """Initialize Gmail SMTP configuration"""
        self.smtp_server = settings.GMAIL_SMTP_SERVER
        self.smtp_port = settings.GMAIL_SMTP_PORT
        self.email = settings.GMAIL_EMAIL
        self.password = settings.GMAIL_APP_PASSWORD
        
        if self.email and self.password:
            app_logger.info("✅ Gmail service initialized")
        else:
            app_logger.warning("⚠️ Gmail credentials not configured")
    
    def send_email(
        self,
        to_email: str,
        subject: str,
        body: str,
        html_body: Optional[str] = None,
        attachments: Optional[List[str]] = None
    ) -> bool:
        """
        Send an email via Gmail
        
        Args:
            to_email: Recipient email address
            subject: Email subject
            body: Plain text body
            html_body: Optional HTML body
            attachments: Optional list of file paths to attach
        
        Returns:
            True if successful, False otherwise
        """
        if not self.email or not self.password:
            app_logger.error("❌ Gmail credentials not configured")
            return False
        
        try:
            # Create message
            msg = MIMEMultipart('alternative')
            msg['From'] = self.email
            msg['To'] = to_email
            msg['Subject'] = subject
            
            # Attach plain text
            msg.attach(MIMEText(body, 'plain'))
            
            # Attach HTML if provided
            if html_body:
                msg.attach(MIMEText(html_body, 'html'))
            
            # Attach files if provided
            if attachments:
                for file_path in attachments:
                    if os.path.exists(file_path):
                        with open(file_path, 'rb') as f:
                            part = MIMEBase('application', 'octet-stream')
                            part.set_payload(f.read())
                        
                        encoders.encode_base64(part)
                        filename = os.path.basename(file_path)
                        part.add_header(
                            'Content-Disposition',
                            f'attachment; filename= {filename}'
                        )
                        msg.attach(part)
            
            # Connect and send
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.email, self.password)
                server.send_message(msg)
            
            app_logger.info(f"✅ Email sent to {to_email}")
            return True
            
        except Exception as e:
            app_logger.error(f"❌ Failed to send email: {str(e)}")
            return False
    
    def send_report(
        self,
        to_email: str,
        report_data: dict,
        attachment_path: Optional[str] = None
    ) -> bool:
        """
        Send a formatted report email
        
        Args:
            to_email: Recipient email
            report_data: Dictionary with report data
            attachment_path: Optional PDF report path
        
        Returns:
            True if successful
        """
        subject = f"Regnova Report: {report_data.get('title', 'Document Analysis')}"
        
        # Plain text body
        body = f"""
Hello,

Here is your Regnova Knowledge Assistant report:

Title: {report_data.get('title', 'N/A')}
Date: {report_data.get('date', 'N/A')}
Summary: {report_data.get('summary', 'N/A')}

Files Analyzed: {report_data.get('file_count', 0)}
Total Chunks: {report_data.get('chunk_count', 0)}

Best regards,
Regnova Knowledge Assistant
"""
        
        # HTML body
        html_body = f"""
<html>
<body style="font-family: Arial, sans-serif;">
    <h2 style="color: #2563eb;">Regnova Knowledge Assistant Report</h2>
    <h3>{report_data.get('title', 'Document Analysis')}</h3>
    
    <p><strong>Date:</strong> {report_data.get('date', 'N/A')}</p>
    <p><strong>Summary:</strong></p>
    <p>{report_data.get('summary', 'N/A')}</p>
    
    <hr>
    
    <p><strong>Files Analyzed:</strong> {report_data.get('file_count', 0)}</p>
    <p><strong>Total Chunks:</strong> {report_data.get('chunk_count', 0)}</p>
    
    <br>
    <p style="color: #666;">Generated by Regnova Knowledge Assistant</p>
</body>
</html>
"""
        
        attachments = [attachment_path] if attachment_path else None
        
        return self.send_email(
            to_email=to_email,
            subject=subject,
            body=body,
            html_body=html_body,
            attachments=attachments
        )
    
    def send_notification(
        self,
        to_email: str,
        notification_type: str,
        message: str
    ) -> bool:
        """
        Send a notification email
        
        Args:
            to_email: Recipient email
            notification_type: Type of notification (e.g., "File Uploaded", "Processing Complete")
            message: Notification message
        
        Returns:
            True if successful
        """
        subject = f"Regnova Notification: {notification_type}"
        
        body = f"""
Hello,

{message}

Best regards,
Regnova Knowledge Assistant
"""
        
        return self.send_email(
            to_email=to_email,
            subject=subject,
            body=body
        )


# Global instance
gmail_service = GmailService()
